// https://rapidapi.com/justin-WFnsXH_t6/api/exercisedb

export const sliderImages = [
  require("../assets/images/slide1.png"),
  require("../assets/images/slide3.png"),
  require("../assets/images/slide2.png"),
  require("../assets/images/slide4.png"),
  require("../assets/images/slide5.png"),
];

export const bodyParts = [
  {
    name: "back",
    image: require("../assets/images/back.png"),
  },
  {
    name: "cardio",
    image: require("../assets/images/cardio.png"),
  },

  {
    name: "lower arms",
    image: require("../assets/images/lowerArms.png"),
  },
  {
    name: "lower legs",
    image: require("../assets/images/lowerLegs.png"),
  },
  {
    name: "chest",
    image: require("../assets/images/chest.png"),
  },
  {
    name: "neck",
    image: require("../assets/images/neck.png"),
  },
  {
    name: "shoulders",
    image: require("../assets/images/shoulders.png"),
  },
  {
    name: "upper arms",
    image: require("../assets/images/upperArms.png"),
  },
  {
    name: "upper legs",
    image: require("../assets/images/upperLegs.png"),
  },
  {
    name: "waist",
    image: require("../assets/images/waist.png"),
  },
];

export const demoExercises = [
  {
    bodyPart: "back",
    equipment: "cable",
    gifUrl: "https://v2.exercisedb.io/image/Nhlkzq2aHhC4ZZ",
    id: "0007",
    instructions: [
      "Sit on the cable machine with your back straight and feet flat on the ground.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "alternate lateral pulldown",
    secondaryMuscles: ["biceps", "rhomboids"],
    target: "lats",
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/rtn33IUAlraT7X",
    id: "3293",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
      "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
      "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
      "Alternate sides with each repetition.",
    ],
    name: "archer pull up",
    secondaryMuscles: ["biceps", "forearms"],
    target: "lats",
  },
  {
    bodyPart: "back",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/7FZLLJMS6n2v9P",
    id: "0015",
    instructions: [
      "Adjust the machine to your desired weight and height.",
      "Place your hands on the parallel bars with a close grip, palms facing each other.",
      "Hang from the bars with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the bars.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "assisted parallel close grip pull-up",
    secondaryMuscles: ["biceps", "forearms"],
    target: "lats",
  },
  {
    bodyPart: "back",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/ShkXVp2r3gYheH",
    id: "0017",
    instructions: [
      "Adjust the machine to your desired weight and height settings.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the handles.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "assisted pull-up",
    secondaryMuscles: ["biceps", "forearms"],
    target: "lats",
  },
  {
    bodyPart: "back",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/R0R3dBdxFNJbU4",
    id: "1431",
    instructions: [
      "Adjust the machine to your desired assistance level.",
      "Stand on the foot platform and grip the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Keep your chest up and shoulders back, engage your core, and slightly bend your knees.",
      "Pull your body up by flexing your elbows and driving your elbows down towards your sides.",
      "Continue pulling until your chin is above the bar.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "assisted standing chin-up",
    secondaryMuscles: ["biceps", "forearms"],
    target: "lats",
  },
  {
    bodyPart: "back",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/Zkkr8RUTx1EH19",
    id: "1432",
    instructions: [
      "Adjust the machine to your desired weight and height settings.",
      "Stand facing the machine with your feet shoulder-width apart.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your lats and biceps, and pull yourself up towards the handles.",
      "Pause for a moment at the top, squeezing your back muscles.",
      "Slowly lower yourself back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "assisted standing pull-up",
    secondaryMuscles: ["biceps", "forearms"],
    target: "lats",
  },
  {
    bodyPart: "back",
    equipment: "stability ball",
    gifUrl: "https://v2.exercisedb.io/image/isNStcOVrYy2Ik",
    id: "1314",
    instructions: [
      "Place the stability ball on the ground and lie face down on top of it, with your hips resting on the ball and your feet against a wall or other stable surface.",
      "Position your hands behind your head or crossed over your chest.",
      "Engage your core and slowly lift your upper body off the ball, extending your back until your body forms a straight line from your head to your heels.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "back extension on exercise ball",
    secondaryMuscles: ["glutes", "hamstrings"],
    target: "spine",
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/grBNdcZ1qVeu-J",
    id: "3297",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "Bend your knees and tuck them towards your chest.",
      "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.",
      "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "back lever",
    secondaryMuscles: ["biceps", "forearms", "core"],
    target: "upper back",
  },
  {
    bodyPart: "back",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/D20NOSZgcjLCfS",
    id: "1405",
    instructions: [
      "Stand tall with your feet shoulder-width apart.",
      "Extend your arms straight out in front of you, parallel to the ground.",
      "Cross your arms in front of your body, with your right arm over your left arm.",
      "Interlock your fingers and rotate your palms away from your body.",
      "Slowly raise your arms up and away from your body, feeling a stretch in your back and chest.",
      "Hold the stretch for 15-30 seconds, then release.",
      "Repeat on the opposite side.",
    ],
    name: "back pec stretch",
    secondaryMuscles: ["shoulders", "chest"],
    target: "lats",
  },
  {
    bodyPart: "back",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/itYyMPaWJYf9eJ",
    id: "0970",
    instructions: [
      "Attach the band to a pull-up bar or sturdy anchor point.",
      "Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.",
      "Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.",
      "Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "band assisted pull-up",
    secondaryMuscles: ["biceps", "forearms"],
    target: "lats",
  },
];
